### ISSUE TITLE
terminal display color

### ISSUE THREAD

**Issue by diwu1989** [jupyter/jupyter_console#76] opened 2016-05-31 07:28 UTC
Jupyter terminal doesn't seem to display color correctly
![image](https://cloud.githubusercontent.com/assets/380950/15666604/85728710-26c6-11e6-8a4e-b68e56127ab1.png)
should be more like
![image](https://cloud.githubusercontent.com/assets/380950/15666611/92dc1c5e-26c6-11e6-8359-d218c2b0dbc6.png)

**Comment by takluyver** [comment] 2016-05-31 08:51
That's weird, colours have always worked for me.

**Comment by takluyver** [comment] 2016-05-31 08:54
Also, btw, this isn't the relevant repo - this repo is for `jupyter console`, which runs *inside* a terminal. The terminal page in the notebook is part of `jupyter/notebook`, although any bugs in the terminal itself are more likely to be part of [term.js](https://github.com/chjj/term.js/) (the frontend) or [terminado](https://github.com/takluyver/terminado) (the backend).

**Comment by takluyver** [comment] 2016-06-28 16:35
Closing as it's not part of this repo. I still have no idea what might be causing it - check if you see the same in another browser. If it's still a problem, please open an issue on one of those repos I mentioned (probably `notebook` - even though it's probably not a bug there, it's a reasonable starting point).

**Closed by takluyver** 2016-06-28 16:35 UTC
