### ISSUE TITLE
kernal not recognising change in file imported from different directory

### ISSUE THREAD

**Issue by deathcod** [jupyter/jupyter_console#112] opened 2016-10-23 05:50 UTC
This was a strange problem I faced while coding , 
Suppose x/code.ipynb is my current working notebook 
Suppose x/y/z.py is the file I imported

Now if I make changes in z.py and I run the cell in code.py the changes are not getting reflected. If I restart the kernel it detects the changes and returns the correct result.

**Comment by takluyver** [comment] 2016-10-23 08:22
That's normal for imports in Python; `z.py` is loaded once when you first import it, and anything you use from it later comes from when you first import it.

IPython has an extension called [autoreload](http://ipython.readthedocs.io/en/stable/config/extensions/autoreload.html) which checks if imported files have changed and reloads them.

I'll close this because it's not a bug, but feel free to continue discussion in the comments if you want.

**Closed by takluyver** 2016-10-23 08:22 UTC
