### ISSUE TITLE
copy paste

### ISSUE THREAD

**Issue by feldman4** [jupyter/jupyter_console#2] opened 2015-05-24 19:00 UTC
Copy and paste to/from the Jupyter terminal isn't working.

**Comment by Carreau** [comment] 2015-05-24 19:51
You are speaking about the thing you get with `ipython console` ? Cause it works here.

**Comment by takluyver** [comment] 2015-05-24 21:31
I suspect @feldman4 means the terminal in the notebook interface - in which case see jupyter/notebook#104. It's probably something that needs fixing in term.js, though.

**Comment by feldman4** [comment] 2015-05-25 14:24
@takluyver that's right, is there a working workaround? right click and ctrl+a => ctrl+v did nothing for me.

**Comment by rgbkrk** [comment] 2015-05-25 14:28
Closing as duplicate of jupyter/notebook#104. Continue the conversation there please.

**Closed by rgbkrk** 2015-05-25 14:28 UTC
