### ISSUE TITLE
%reset hang 

### ISSUE THREAD

**Issue by ocehugo** [jupyter/jupyter_console#67] opened 2016-03-22 05:24 UTC
Calling two times the %reset magic cause the kernel to hang

**Comment by ocehugo** [comment] 2016-03-22 06:27
Using --Session.debug=True avoid the problem

**Comment by takluyver** [comment] 2016-03-22 10:44
I suspect this is another symptom of the same cause as #66. Both %reset and %pdb prompt for input, which requires the kernel to send a message to the frontend and wait for a response. Something must be going wrong with that.

I also can't reproduce this.

**Comment by takluyver** [comment] 2016-03-22 22:59
Closing following discussion in #66. We can reopen one of these if we decide there's something to fix here.

**Closed by takluyver** 2016-03-22 22:59 UTC
