### ISSUE TITLE
WARNING: The kernel did not respond to an is_complete_request. Setting `use_kernel_is_complete` to False.

### ISSUE THREAD

**Issue by ocehugo** [jupyter/jupyter_console#40] opened 2016-01-05 05:26 UTC
Hi,
At apparently random times I start to get this Warning message. It's a annoying thing since after this occurs i need to press enter 2 times to complete any command since the kernel keep waiting for the completion of the command.

jupiter 4.1.0.dev
python 3.5.1
ipython 4.0.1

**Comment by takluyver** [comment] 2016-01-06 13:45
Ping @dsblank - this sounds like the timeout for is_complete_reply is not long enough.

**Comment by dsblank** [comment] 2016-01-06 14:30
I'll take a look.

**Comment by dsblank** [comment] 2016-01-06 14:32
@ocehugo You are using `jupyter console` or `ipython console` rather than just `ipython`? You on a local machine?

**Comment by ocehugo** [comment] 2016-01-07 00:25
@dsblank - jupiter-console... I think i was not clear: after this happening ALL the following commands wait for a reply ( double enter). Is not *just* the current line/command, so there is a `if` missing or a big jump happening  somewhere in the code after the exception or check...

**Comment by dsblank** [comment] 2016-01-07 01:21
@ocehugo I understand. Some question:

1. Why are you using `jupyter-console` rather than `ipython`?
1. Can you run with the `--debug` flag and show output?
1. Are you running on a slow computer, or where the kernel is on a different computer from the console?

**Comment by ocehugo** [comment] 2016-01-07 01:24
@dsblank 

1. Good question. Don't know...upgraded and this command show up and i was thinking this was the new way.
2. Yeap. with --debug nothing extra is showed

3. Kernel is local && not a slow machine.

**Comment by dsblank** [comment] 2016-01-07 01:29
> Good question. Don't know...upgraded and this command show up and i was thinking this was the new way.

You can run `ipython` as a workaround as it doesn't use the client/server arcitecture.

> Yeap. with --debug nothing extra is showed

There should be quite a bit more output: `jupyter-console --debug` should show many details.

**Comment by ocehugo** [comment] 2016-01-07 02:04
1. I know that using ipython doesn't cause this ( im using it now).

I was thinking you would want the debug from when the warning was raised...the debug output when starting jupyter is below ( i'm using a modified profile but this doesn't change the outcomes):

` jupyter-console --debug
[ZMQTerminalIPythonApp] Config changed:
[ZMQTerminalIPythonApp] {'ZMQTerminalIPythonApp': {'log_level': 10}}
[ZMQTerminalIPythonApp] IPYTHONDIR set to: /Users/ochugo/.ipython
[ZMQTerminalIPythonApp] Using existing profile dir: '/Users/ochugo/.ipython/profile_default'
[ZMQTerminalIPythonApp] Searching path ['/Users/ochugo', '/Users/ochugo/.ipython/profile_default', '/usr/local/etc/ipython', '/etc/ipython'] for config files
[ZMQTerminalIPythonApp] Attempting to load config file: ipython_config.py
[ZMQTerminalIPythonApp] Attempting to load config file ipython_config.py in path /etc/ipython
[ZMQTerminalIPythonApp] Attempting to load config file ipython_config.json in path /etc/ipython
[ZMQTerminalIPythonApp] Attempting to load config file ipython_config.py in path /usr/local/etc/ipython
[ZMQTerminalIPythonApp] Attempting to load config file ipython_config.json in path /usr/local/etc/ipython
[ZMQTerminalIPythonApp] Attempting to load config file ipython_config.py in path /Users/ochugo/.ipython/profile_default
[ZMQTerminalIPythonApp] Attempting to load config file ipython_config.json in path /Users/ochugo/.ipython/profile_default
[ZMQTerminalIPythonApp] Loaded config file: /Users/ochugo/.ipython/profile_default/ipython_config.py
[ZMQTerminalIPythonApp] Config changed:
[ZMQTerminalIPythonApp] {'ZMQTerminalIPythonApp': {'log_level': 10}, 'HistoryManager': {'hist_file': '/Users/ochugo/docs/python/ipython_hist.sqlite', 'enabled': True, 'enable': True}, 'TerminalInteractiveShell': {'automagic': True, 'editor': 'mvim', 'history_length': 1000000, 'cache_size': 5000, 'multiline_history': True, 'readline_use': True, 'pager': 'vimpager'}, 'TerminalIPythonApp': {'matplotlib': 'tk', 'gui': 'tk', 'log_datefmt': '%Y-%m-%d'}, 'InteractiveShellApp': {'exec_lines': ['import time', 'import numpy as np', 'import matplotlib.pyplot as plt', 'import matplotlib.dates as mdates', 'import netCDF4 as nc', 'from mpl_toolkits.basemap import Basemap', 'from astropy import units as U', 'from astropy import constants as G', 'from astropy.coordinates import SkyCoord', 'from romstools import dotdictify as dotdict'], 'matplotlib': 'tk', 'gui': 'tk', 'extensions': ['autoreload']}}
[ZMQTerminalIPythonApp] Attempting to load config file ipython_config.py in path /Users/ochugo
[ZMQTerminalIPythonApp] Attempting to load config file ipython_config.json in path /Users/ochugo
[ZMQTerminalIPythonApp] Attempting to load config file: jupyter_console_config
[ZMQTerminalIPythonApp] Attempting to load config file jupyter_console_config.py in path /etc/ipython
[ZMQTerminalIPythonApp] Attempting to load config file jupyter_console_config.json in path /etc/ipython
[ZMQTerminalIPythonApp] Attempting to load config file jupyter_console_config.py in path /usr/local/etc/ipython
[ZMQTerminalIPythonApp] Attempting to load config file jupyter_console_config.json in path /usr/local/etc/ipython
[ZMQTerminalIPythonApp] Attempting to load config file jupyter_console_config.py in path /Users/ochugo/.ipython/profile_default
[ZMQTerminalIPythonApp] Attempting to load config file jupyter_console_config.json in path /Users/ochugo/.ipython/profile_default
[ZMQTerminalIPythonApp] Attempting to load config file jupyter_console_config.py in path /Users/ochugo
[ZMQTerminalIPythonApp] Attempting to load config file jupyter_console_config.json in path /Users/ochugo
[ZMQTerminalIPythonApp] Connection File not found: /Users/ochugo/Library/Jupyter/runtime/kernel-19924.json
[ZMQTerminalIPythonApp] Native kernel (python3) available from /usr/local/lib/python3.5/site-packages/ipykernel/resources
[ZMQTerminalIPythonApp] Starting kernel: ['/usr/local/opt/python3/bin/python3.5', '-m', 'ipykernel', '-f', '/Users/ochugo/Library/Jupyter/runtime/kernel-19924.json']
[ZMQTerminalIPythonApp] Connecting to: tcp://127.0.0.1:50084
[ZMQTerminalIPythonApp] connecting shell channel to tcp://127.0.0.1:50081
[ZMQTerminalIPythonApp] Connecting to: tcp://127.0.0.1:50081
[ZMQTerminalIPythonApp] connecting iopub channel to tcp://127.0.0.1:50082
[ZMQTerminalIPythonApp] Connecting to: tcp://127.0.0.1:50082
[ZMQTerminalIPythonApp] connecting stdin channel to tcp://127.0.0.1:50083
[ZMQTerminalIPythonApp] Connecting to: tcp://127.0.0.1:50083
[ZMQTerminalIPythonApp] connecting heartbeat channel to tcp://127.0.0.1:50085
Jupyter Console 4.1.0.dev

[ZMQTerminalIPythonApp] Loading IPython extensions...
[ZMQTerminalIPythonApp] Loading IPython extension: storemagic
[ZMQTerminalIPythonApp] Loading IPython extension: autoreload
[ZMQTerminalIPythonApp] Starting IPython's mainloop...
`

**Comment by dsblank** [comment] 2016-01-07 02:13
> I know that using ipython doesn't cause this ( im using it now).

I only mention using ipython because it works without a client/server and is a work-around. You should use it, unless you need jupyter-console for some reason.

This could be caused by the libraries that you are loading in the modified profile, and not providing enough time.

Two things you could try:

1. Do you still get this behavior when you don't run with the modified profile with jupyter-console?
2. You could try adjusting `jupyter_console/interactiveshell.py` line 663 to a larger number (say, change 0.05 to 1.00)

**Comment by ocehugo** [comment] 2016-01-07 02:21
1. As i said : yes. I removed the profile and jupiter created a new one and the warning was still happening.

2. I did that and it worked.

**Comment by dsblank** [comment] 2016-01-07 02:26
Ok, thanks! I need to do some work then.

**Comment by dsblank** [comment] 2016-01-07 11:28
@takluyver How should we go about fixing this?

* make the 0.05 a longer default?
* make it a config option?

I guess making it much longer (say 0.5 or 1.0) won't be too bad, because as soon as it fails once, it won't try again.

**Comment by takluyver** [comment] 2016-01-07 11:38
If @ocehugo saw this failure with the kernel on the same machine, we definitely need to increase the default, regardless of what else we do. I think it probably also makes sense to make it a configurable, so that if other people run into this problem, they can try different values without having to find and edit the code.

**Comment by dsblank** [comment] 2016-01-07 12:38
Added a configurable, `--ZMQTerminalInteractiveShell.kernel_is_complete_timeout=1.0`

https://github.com/jupyter/jupyter_console/pull/44

**Comment by minrk** [comment] 2016-01-07 12:42
closed by #40

**Closed by minrk** 2016-01-07 12:42 UTC

**Comment by ocehugo** [comment] 2016-01-22 03:46
Just 2%:
With the added configurable the behaviour still continue to create some hassle. If in any time the kernel is complete timeout is raised the kernel keeps waiting the completion of the command for all subsequent commands. I believe it should be just for the immediate command after the warning, coming back to default behaviour after it.

Example:
So say you have a notebook kernel running and a ipython console also connected to it. You put a long  command to running( say in the notebook).  While running and after the is_complete_timeout , you go to the console and try a new command. This raise the warning (since it's still executing in notebook and no feedback from the kernel is returned). Now all commands in the current console will wait for completion making the user required to press 2 times the return key for every new command. I would expect something like this required for the first one or two commands, but not for the entire session from the warning is raised.

**Comment by dsblank** [comment] 2016-01-22 12:00
Thanks for the comments @ocehugo ... this is useful feedback, as I was unsure of all of the implications of these changes. Note that it isn't just "pressing enter twice" but there needs to be a blank line to signal the end of an expression. Also note that this interface must work for all languages.

I understand exactly what you mean. We could try each time to get a response from the server in fact, never giving up completely. But now the response from the server also includes indentation. I would be hesitant to make additional complications because this can be confusing to the user. Why did it stop indenting? Why do sometimes I need the blank line?

Of course, one can disconnect and reconnect. If there is a %reset magic, maybe that could reset the setting.

**Comment by damianavila** [comment] 2016-01-25 13:31
> closed by #40

Closed by #44 :wink:

**Comment by takluyver** [comment] 2016-01-27 12:19
Rats, I didn't think of this. Of course, if there's another client connected, the kernel could be busy when we send the `is_complete_request`.

I don't think a magic is the right solution here: magics act on the kernel, and not all kernels implement them, while this problem could affect any kernel. On the plus side, if you're using the console connected to a notebook kernel, you can close the console with `exit(keep_kernel=True)` and start it again without losing your namespace.

Maybe the frontend should be aware of the kernel's busy/idle state, and temporarily switch to fallback mode if the kernel is busy. I think that's a bit trickier, though: it would need a separate thread pulling messages off iopub, and a way to get those messages back to the main thread.
